data:
  url: https://wis.fit.vutbr.cz/FIT/st/course-reg.php.cs
  telegram:
    token: 281271685:AAGD0YznrFPbh6Xgt37V_SRwg1EXUaXddzA

  users:
    hurzhii:
      login: xhurzh00
      password: pumduj6are
