data:
  help: "Привет, я бот который поможет тебе не вылететь из вуза. Я проверяю каждые 5 минут сайт VUT, и как только там появится регистрация на следующий семестр, я вам напишу. Вы можете использовать следующие команды:

/now - получить нынешний статус регистрации

/exams - мое мнение на то, как вы сдадите экзамены

/help - прочитать информацию еще раз

/start - получить информацию обо мне

/nodes - я сравниваю количество дом елементов которое было раньше и их количество сейчас. Эта команда покажет вам сколько их на данный момент

В будущем, я планирую стать умнее и иметь возможность отвечать на все ваши вопросы связанные с учебой в этом вузе."

  url: https://wis.fit.vutbr.cz/FIT/st/course-reg.php.cs
  telegram:
    token: 281271685:AAGD0YznrFPbh6Xgt37V_SRwg1EXUaXddzA

  users:
    hurzhii:
      login: xhurzh00
      password: pumduj6are
