adapter: postgresql
database: new-vut-semester
encoding: unicode
pool: 5
timeout: 5000
host: localhost
# heroku run rake db:migrate --app new-vut-semester
# heroku addons:create heroku-postgresql:hobby-dev
# heroku config
# heroku pg
# heroku config:add DATABASE_URL=postgres://cfnasjptwszmxg:e9c70cbf5d7a0753571e48f69a72ff1870b68d4c855f09fba0cb43536e32109d@ec2-54-247-120-169.eu-west-1.compute.amazonaws.com:5432/da7cjdcnan3qkr
